language: python
python:
  - "3.8"

install:
  - pip install -r requirements.txt

env:
  - TEST_DB_URL=postgresql://postgres:@localhost/travis_ci_test

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - pytest src/