language: python
python:
  - "3.8"

install:
  - pip install -r requirements.txt

env:
  - TEST_DB_URL=postgresql://postgres:@localhost/travis_ci_test TEST_MODE=1

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - coverage run  --source=src/ -m pytest src/

after_success:
  - bash <(curl -s https://codecov.io/bash)