version: '2.0'

services:
  web:
    build: .
    ports:
      - "8000:8000"

    environment:
      TEST_DB_URL: "postgresql://postgres:postgres@db:5432/minimo_db"
      TEST_MODE: 1

    command: test

  db:
    image: postgres

    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'minimo_db'



    