"""empty message

Revision ID: a9bb30c7d940
Revises: d00585ec08e2
Create Date: 2020-07-22 23:50:00.430215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9bb30c7d940'
down_revision = 'd00585ec08e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=20), nullable=False),
    sa.Column('is_good', sa.Boolean(), nullable=False),
    sa.Column('id_theme', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_theme'], ['theme.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('id_theme', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_theme'], ['theme.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('name', 'firstname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('theme', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('theme', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('name', 'firstname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('item')
    op.drop_table('feature')
    # ### end Alembic commands ###
