"""empty message

Revision ID: d00585ec08e2
Revises: dce28e5e21c5
Create Date: 2020-07-22 23:34:42.520606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd00585ec08e2'
down_revision = 'dce28e5e21c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
