"""empty message

Revision ID: dce28e5e21c5
Revises: 
Create Date: 2020-07-22 23:27:06.621294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dce28e5e21c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('name', sa.Column('id_theme', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'name', 'theme', ['id_theme'], ['id'])
    op.drop_column('name', 'theme')
    op.drop_column('name', 'language')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('name', sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('name', sa.Column('theme', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'name', type_='foreignkey')
    op.drop_column('name', 'id_theme')
    op.drop_table('theme')
    # ### end Alembic commands ###
