"""empty message

Revision ID: 3e1f5d9f9ef2
Revises: 37b995c76607
Create Date: 2020-07-31 22:23:54.929246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e1f5d9f9ef2'
down_revision = '37b995c76607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linkfeaturetheme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_theme', sa.Integer(), nullable=False),
    sa.Column('id_feature', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_feature'], ['feature.id'], ),
    sa.ForeignKeyConstraint(['id_theme'], ['theme.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('linkitemtheme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_theme', sa.Integer(), nullable=False),
    sa.Column('id_item', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_item'], ['item.id'], ),
    sa.ForeignKeyConstraint(['id_theme'], ['theme.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('linknametheme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_theme', sa.Integer(), nullable=False),
    sa.Column('id_name', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_name'], ['name.id'], ),
    sa.ForeignKeyConstraint(['id_theme'], ['theme.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('linknametheme')
    op.drop_table('linkitemtheme')
    op.drop_table('linkfeaturetheme')
    # ### end Alembic commands ###
