"""empty message

Revision ID: 6b48a14810ad
Revises: 3e1f5d9f9ef2
Create Date: 2020-08-01 19:53:40.766026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b48a14810ad'
down_revision = '3e1f5d9f9ef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'name', ['firstname', 'lastname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'name', type_='unique')
    # ### end Alembic commands ###
