"""empty message

Revision ID: ceb5fedfe73b
Revises: a025c2020370
Create Date: 2020-08-01 20:36:51.046442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceb5fedfe73b'
down_revision = 'a025c2020370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'linkfeaturetheme', ['id_feature', 'id_theme'])
    op.create_unique_constraint(None, 'linkitemtheme', ['id_item', 'id_theme'])
    op.create_unique_constraint(None, 'linknametheme', ['id_name', 'id_theme'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'linknametheme', type_='unique')
    op.drop_constraint(None, 'linkitemtheme', type_='unique')
    op.drop_constraint(None, 'linkfeaturetheme', type_='unique')
    # ### end Alembic commands ###
